# Estableciendo el lenguaje
language: node_js
cache: 
  directories: 
    - node_modules
    - ~/.npm

# Version de Node
node_js:
  - '12'

# Hasta 3 versiones atras
git:
  depth: 3


# Ejecutando scripts programados en .package.json
script: 
  - yarn build

deploy: 
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master